language: node_js
node_js:
  - "6.9"
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  - NODE_ENV='test'
script:
  - npm test
  - yarn add global react-native-cli
matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      sudo: required
      node_js: false
      before_cache:
        - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/modules-2/modules-2.lock # Avoid to repack it due locks
        - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/3.3/classAnalysis/classAnalysis.lock
        - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/3.3/jarSnapshots/jarSnapshots.lock
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/gradle/caches/
          - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
      before_install:
        - nvm install 7
        - node --version
        - travis_retry curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - travis_retry sudo apt-get update -qq
        - travis_retry sudo apt-get install -y -qq yarn
        - echo yes | sdkmanager "platforms;android-26"
      android:
        components:
          - tools
          - build-tools-27.0.2
          - extra-android-support
          - extra-google-m2repository
          - extra-android-m2repository
          - platform-tools
          - tools
      licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
      script:
        - yarn install
        - cd android && ./gradlew assembleDebug