export const GET_CLUES = 'GET_CLUES';
export const GET_CLUES_FAIL = 'GET_CLUES_FAIL';

export const GET_TOKEN = 'GET_TOKEN';
export const GET_TOKEN_FAIL = 'GET_TOKEN_FAIL';

export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL';

export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const SHOW_USUARIO_CLUES = 'SHOW_USUARIO_CLUES';
export const INSERT_SELECT_CLUES = 'INSERT_SELECT_CLUES';

//INCIDENCIAS
export const SHOW_INCIDENCIAS = 'SHOW_INCIDENCIAS';
export const SHOW_INCIDENCIAS_SUCCESS = 'SHOW_INCIDENCIAS_SUCCESS';
export const SHOW_INCIDENCIAS_FAIL = 'SHOW_INCIDENCIAS_FAIL';
export const INSERT_NEW_PHOTO_REFERENCIA = 'INSERT_NEW_PHOTO_REFERENCIA';
export const INSERT_NEW_PHOTO_REFERENCIA_SUCCESS = 'INSERT_NEW_PHOTO_REFERENCIA_SUCCESS';

//CENSO
export const SHOW_CENSO = 'SHOW_CENSO';
export const SHOW_CENSO_SUCCESS = 'SHOW_CENSO_SUCCESS';
export const SHOW_CENSO_FAIL = 'SHOW_CENSO_FAIL';

export const MUNICIPIO_CHANGED = 'MUNICIPIO_CHANGED';
export const LOCALIDAD_CHANGED = 'LOCALIDAD_CHANGED';
export const ESTADO_EMBARAZO_CHANGED = 'ESTADO_EMBARAZO_CHANGED';
export const DERECHOHABIENTE_CHANGED = 'DERECHOHABIENTE_CHANGED';
export const CURP_CHANGED = 'CURP_CHANGED';
export const NOMBRE_CHANGED = 'NOMBRE_CHANGED';
export const PATERNO_CHANGED = 'PATERNO_CHANGED';
export const MATERNO_CHANGED = 'MATERNO_CHANGED';
export const DIRECCION_CHANGED = 'DIRECCION_CHANGED';
export const CELULAR_CHANGED = 'CELULAR_CHANGED';
export const FECHA_NACIMIENTO_CHANGED = 'FECHA_NACIMIENTO_CHANGED';

export const INSERT_NEW_PERSON = 'INSERT_NEW_PERSON';
export const INSERT_NEW_PERSON_SUCCESS = 'INSERT_NEW_PERSON_SUCCESS';

//ESTADO FUERZA
export const SHOW_ESTADO_FUERZA = 'SHOW_ESTADO_FUERZA';
export const SHOW_ESTADO_FUERZA_SUCCESS = 'SHOW_ESTADO_FUERZA_SUCCESS';
export const SHOW_ESTADO_FUERZA_FAIL = 'SHOW_ESTADO_FUERZA_FAIL';

export const CREATE_ITEM_ARRAY = 'CREATE_ITEM_ARRAY';
export const CREATE_CARTERA_SERVICIOS_ARRAY = 'CREATE_CARTERA_SERVICIOS_ARRAY';
export const CREATE_ESTADO_FUERZA_OBJECT = 'CREATE_ESTADO_FUERZA_OBJECT';

//CLUES
export const SHOW_CLUES = 'SHOW_CLUES';
export const SHOW_CLUES_SUCCESS = 'SHOW_CLUES_SUCCESS';
export const SHOW_CLUES_FAIL = 'SHOW_CLUES_FAIL';

//Catalogs
export const SHOW_MUNICIPIOS = 'SHOW_MUNICIPIOS';
export const SHOW_MUNICIPIOS_SUCCESS = 'SHOW_MUNICIPIOS_SUCCESS';
export const SHOW_LOCALIDADES = 'SHOW_LOCALIDADES';
export const SHOW_LOCALIDADES_SUCCESS = 'SHOW_LOCALIDADES_SUCCESS';
export const SHOW_ESTADOS_EMBARAZOS = 'SHOW_ESTADOS_EMBARAZOS';
export const SHOW_ESTADOS_EMBARAZOS_SUCCESS = 'SHOW_ESTADOS_EMBARAZOS_SUCCESS';
export const SHOW_DERECHOHABIENTES = 'SHOW_DERECHOHABIENTES';
export const SHOW_DERECHOHABIENTES_SUCCESS = 'SHOW_DERECHOHABIENTES_SUCCESS';
export const SHOW_TURNOS = 'SHOW_TURNOS';
export const SHOW_TURNOS_SUCCESS = 'SHOW_TURNOS_SUCCESS';

