export const GET_CLUES = 'GET_CLUES';
export const GET_CLUES_FAIL = 'GET_CLUES_FAIL';

export const GET_TOKEN = 'GET_TOKEN';
export const GET_TOKEN_FAIL = 'GET_TOKEN_FAIL';

export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL';

export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const SHOW_USUARIO_CLUES = 'SHOW_USUARIO_CLUES';
export const INSERT_SELECT_CLUES = 'INSERT_SELECT_CLUES';

export const SHOW_INCIDENCIAS = 'SHOW_INCIDENCIAS';
export const SHOW_INCIDENCIAS_SUCCESS = 'SHOW_INCIDENCIAS_SUCCESS';
export const SHOW_INCIDENCIAS_FAIL = 'SHOW_INCIDENCIAS_FAIL';

export const NEXT_PAGE = 'NEXT_PAGE';

export const SEARCH_CHANGED = 'SEARCH_CHANGED';

export const SHOW_CENSO = 'SHOW_CENSO';
export const SHOW_CENSO_SUCCESS = 'SHOW_CENSO_SUCCESS';
export const SHOW_CENSO_FAIL = 'SHOW_CENSO_FAIL';

export const SHOW_CLUES = 'SHOW_CLUES';
export const SHOW_CLUES_SUCCESS = 'SHOW_CLUES_SUCCESS';
export const SHOW_CLUES_FAIL = 'SHOW_CLUES_FAIL';
